version: '12.5.1'
services:
  front:
    build: ./
    environment:
      - PORT=3000
  cypress:
    image: cypress/included:cypress-12.5.1-node-16.18.1-chrome-110.0.5481.96-1-ff-109.0-edge-110.0.1587.41-1
    entrypoint: /bin/sh -c "npm install @esbuild/linux-x64 && CYPRESS_BASE_URL=http://front:3000 cypress run --headless --browser chrome"
    depends_on:
      - front
    working_dir: /test
    volumes:
      - ./:/test
      - /tmp/.X11-unix:/tmp/.X11-unix